title: 똑똑한개발자 기술 블로그
email: contact@toktokhan.dev
description: |
  세상을 놀라게 할 IT 서비스를
  함께 성장하며 만들어갑니다.
baseurl: ""
url: "https://tech.toktokhan.dev"
timezone: Asia/Seoul

repository: TokTokHan/TokTokHan.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page/:num/"

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: contact@toktokhan.dev
image: "/assets/images/default_blog_cover.png"
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: "G-SB8V76F3J5"
# facebook:
#   app_id: "1204347326263800"
#   username: nkakao
instagram:
  username: toktokhan.dev
github_url:
  username: TokTokHan
